### ISSUE TITLE
NPM Release of v0.2.6

### ISSUE THREAD

**Issue by ismarslomic** [saintedlama/restify-mongoose#30]
@saintedlama Can you please do NPM release of v0.2.6. I have done all preparation in GitHub, but I dont have access to the NPM package to do the release in NPM.

**Comment by saintedlama** [comment]
Released and added you as owner - need some proof?

```
> npm owner ls
ismarslomic ...
```

:dancers: 

Thanks for making this package a better package as it was before!

**Comment by ismarslomic** [comment]
Thanks! :)
