### ISSUE TITLE
Page size 100 limit ?

### ISSUE THREAD

**Issue by windmaomao** [saintedlama/restify-mongoose#36]
wow, I use this package every day, however recently i got a request that i need to grab more than 100, ex. 1000 or even 5000 records. Is there a way that i can change this behavior quickly without changing source code.

Thank you.

**Comment by windmaomao** [comment]
Fork the repo, needs to make the test work, or just do some manual integration testing. https://github.com/windmaomao/restify-mongoose

**Comment by saintedlama** [comment]
This is a bug. Will touch the code :+1:

**Comment by saintedlama** [comment]
Fixed and :shipit: as version 1.0.0 with some major dependency updates
